export const CHANNELS_LOADED = "CHANNELS_LOADED";
export const CHANNEL_ADDED = "CHANNEL_ADDED";
export const CHANNEL_IS_SET = "CHANNEL_IS_SET";

export const USERS_LOADED = "USERS_LOADED";
export const USER_ADDED = "USER_ADDED";

export const MESSAGES_LOADED = "MESSAGES_LOADED";
export const MESSAGE_ADDED = "MESSAGE_ADDED";

export const SHOW_CUSTOM_ERROR = "SHOW_CUSTOM_ERROR";
export const HIDE_CUSTOM_ERROR = "HIDE_CUSTOM_ERROR";
export const SERVER_ERROR = "SERVER_ERROR";